export type SteamCurrencyInfo = {
    id: number;
    symbol: string;
    name: string;
}

export const STEAM_CURRENCIES: SteamCurrencyInfo[] = [
    {id: 1, symbol: '$', name: 'United States Dollar'},
    {id: 2, symbol: '£', name: 'United Kingdom Pound'},
    {id: 3, symbol: '€', name: 'European Union Euro'},
    {id: 4, symbol: 'CHF', name: 'Swiss Francs'},
    {id: 5, symbol: '₽', name: 'Russian Rouble'},
    {id: 6, symbol: 'zł', name: 'Polish Złoty'},
    {id: 7, symbol: 'R$', name: 'Brazilian Reals'},
    {id: 8, symbol: '¥', name: 'Japanese Yen'},
    {id: 9, symbol: 'kr', name: 'Norwegian Krone'},
    {id: 10, symbol: 'Rp', name: 'Indonesian Rupiah'},
    {id: 11, symbol: 'RM', name: 'Malaysian Ringgit'},
    {id: 12, symbol: '₱', name: 'Philippine Peso'},
    {id: 13, symbol: '$', name: 'Singapore Dollar'},
    {id: 14, symbol: '฿', name: 'Thai Baht'},
    {id: 15, symbol: '₫', name: 'Vietnamese Dong'},
    {id: 16, symbol: '₩', name: 'South Korean Won'},
    {id: 17, symbol: '₺', name: 'Turkish Lira'},
    {id: 18, symbol: '₴', name: 'Ukrainian Hryvnia'},
    {id: 19, symbol: '$', name: 'Mexican Peso'},
    {id: 20, symbol: '$', name: 'Canadian Dollars'},
    {id: 21, symbol: '$', name: 'Australian Dollars'},
    {id: 22, symbol: '$', name: 'New Zealand Dollar'},
    {id: 23, symbol: '¥', name: 'Chinese Renminbi (yuan)'},
    {id: 24, symbol: '₹', name: 'Indian Rupee'},
    {id: 25, symbol: '$', name: 'Chilean Peso'},
    {id: 26, symbol: 'S/', name: 'Peruvian Sol'},
    {id: 27, symbol: '$', name: 'Colombian Peso'},
    {id: 28, symbol: 'R', name: 'South African Rand'},
    {id: 29, symbol: '$', name: 'Hong Kong Dollar'},
    {id: 30, symbol: '$', name: 'New Taiwan Dollar'},
    {id: 31, symbol: '﷼', name: 'Saudi Riyal'},
    {id: 32, symbol: 'د.إ', name: 'United Arab Emirates Dirham'},
    {id: 33, symbol: 'kr', name: 'Swedish Krona'},
    {id: 34, symbol: '$', name: 'Argentine Peso'},
    {id: 35, symbol: '₪', name: 'Israeli New Shekel'},
    {id: 36, symbol: 'Br', name: 'Belarusian Ruble'},
    {id: 37, symbol: '₸', name: 'Kazakhstani Tenge'},
    {id: 38, symbol: 'د.ك', name: 'Kuwaiti Dinar'},
    {id: 39, symbol: '﷼', name: 'Qatari Riyal'},
    {id: 40, symbol: '₡', name: 'Costa Rican Colón'},
    {id: 41, symbol: '$U', name: 'Uruguayan Peso'},
    {id: 42, symbol: 'лв', name: 'Bulgarian Lev'},
    {id: 43, symbol: 'kn', name: 'Croatian Kuna'},
    {id: 44, symbol: 'Kč', name: 'Czech Koruna'},
    {id: 45, symbol: 'kr', name: 'Danish Krone'},
    {id: 46, symbol: 'Ft', name: 'Hungarian Forint'},
    {id: 47, symbol: 'lei', name: 'Romanian Leu'}
];