// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMarketURIToEquippedItemsViaGolang(arg1, arg2) {
  return window['go']['main']['App']['AddMarketURIToEquippedItemsViaGolang'](arg1, arg2);
}

export function GetAppId(arg1) {
  return window['go']['main']['App']['GetAppId'](arg1);
}

export function GetBackground(arg1, arg2) {
  return window['go']['main']['App']['GetBackground'](arg1, arg2);
}

export function GetEquippedItemsViaGolang(arg1, arg2) {
  return window['go']['main']['App']['GetEquippedItemsViaGolang'](arg1, arg2);
}

export function GetGameName(arg1, arg2) {
  return window['go']['main']['App']['GetGameName'](arg1, arg2);
}

export function GetPageBodyViaGolang(arg1) {
  return window['go']['main']['App']['GetPageBodyViaGolang'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSteam32IDViaGolang(arg1, arg2) {
  return window['go']['main']['App']['GetSteam32IDViaGolang'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenCustomURLViaGolang(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenCustomURLViaGolang'](arg1, arg2, arg3);
}

export function PutMarketPriceToEquippedItemViaGolang(arg1, arg2) {
  return window['go']['main']['App']['PutMarketPriceToEquippedItemViaGolang'](arg1, arg2);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}
