// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMarketURIToEquippedItemsViaGolang(arg1:Array<main.EquippedItem>):Promise<Array<main.EquippedItem>>;

export function GetAppId(arg1:string):Promise<string>;

export function GetBackground(arg1:string,arg2:main.Cache):Promise<string>;

export function GetEquippedItemsViaGolang(arg1:string,arg2:string):Promise<Array<main.EquippedItem>>;

export function GetGameName(arg1:string,arg2:main.Cache):Promise<string>;

export function GetPageBodyViaGolang(arg1:string):Promise<string>;

export function GetSteam32IDViaGolang(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenCustomURLViaGolang(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PutMarketPriceToEquippedItemViaGolang(arg1:main.EquippedItem):Promise<main.EquippedItem>;
